### ISSUE TITLE
Question for calculation problem

### ISSUE THREAD

**Issue by nuxlear** [ainize-team/python-level-challenge#53]
https://github.com/ainize-team/python-level-challenge/blob/c0237a63f50bc77da62d08c9b52a844115336cb4/src/static/json/python.json#L166

위 링크로 연결된 문제 (ID: 13)에 궁금한 점이 있습니다. 

정답이 float형이 아니라 int형인데, 단지 연산 순서만 문제로 내기 위해 연산 결과 value가 맞으면 되도록 의도하신 건지 궁금합니다.

**Comment by pengin7384** [comment]
퀴즈의 목적은 말씀해주신 연산 순서에 관한 문제가 맞지만 파이썬2와 3에서 다르게 출력되는 것은 고려하지 못하였습니다. 3기준으로 변경하는게 낫겠네요!

**Comment by pengin7384** [comment]
@nuxlear 피드백 주신 내용 반영하였습니다! 감사합니다 :) #57
